---
- name: Configure SSL for Rsyslog Server
  hosts: rsyslog_server
  vars:
    rsyslog_client_fqdn:
    - app1
    - app2

  become: yes
  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install OpenSSL
    apt:
      name:
      - rsyslog
      - rsyslog-gnutls
      - openssl
      state: present

  - name: Ensure /etc/ssl is traversable
    file:
      path: /etc/ssl
      state: directory
      mode: '0755'

  - name: Ensure /etc/ssl is owned by root
    file:
      path: /etc/ssl
      owner: root
      group: root
      mode: '0755'

  - name: Create SSL directory
    file:
      path: /etc/ssl/rsyslog
      state: directory
      owner: root
      group: syslog
      mode: '0755'

  - name: Generate self-signed SSL certificate
    command: |
      openssl req -new -x509 -days 365 -nodes
        -newkey rsa:2048
        -out /etc/ssl/rsyslog/rsyslog.crt
        -keyout /etc/ssl/rsyslog/rsyslog.key
        -subj "/CN=log.example.com"
        -addext "basicConstraints=critical,CA:TRUE"
    # args:
    #   creates: /etc/ssl/rsyslog/rsyslog.key


  - name: Set permissions on SSL key
    file:
      path: /etc/ssl/rsyslog/rsyslog.key
      owner: root
      group: syslog
      mode: '0640'

  - name: Set permissions on SSL certificate
    file:
      path: /etc/ssl/rsyslog/rsyslog.crt
      owner: root
      group: syslog
      mode: '0644'

  - name: Allow rsyslog to access SSL certs in AppArmor
    lineinfile:
      path: /etc/apparmor.d/local/usr.sbin.rsyslogd
      line: "/etc/ssl/rsyslog/* r,"
      create: yes
    notify: reload apparmor

  - name: Deploy SSL configuration for rsyslog
    template:
      src: templates/rsyslog-server-ssl.conf.j2
      dest: /etc/rsyslog.d/ssl.conf
    notify: restart rsyslog

  - name: Ensure UFW is enabled and running
    ufw:
      state: enabled

  - name: To not block your self when connecting via SSH, allow port 22
    ufw:
      rule: allow
      port: 22
      proto: tcp

  - name: Deny firewall UDP 514 for traditional syslog
    ufw:
      rule: deny
      port: 514
      proto: udp

  - name: Open firewall TCP 6514 for TLS syslog
    ufw:
      rule: allow
      port: 6514
      proto: tcp


  handlers:
  - name: restart rsyslog
    service:
      name: rsyslog
      state: restarted

  - name: reload apparmor
    service:
      name: apparmor
      state: reloaded

- name: Fetch SSL certificate from Rsyslog Server to Ansible Control Node
  hosts: rsyslog_server
  become: yes
  tasks:
  - name: Fetch SSL certificate from server
    fetch:
      src: /etc/ssl/rsyslog/rsyslog.crt
      dest: /tmp/rsyslog_ca.crt
      flat: yes

- name: Configure Unique SSL for Rsyslog Clients
  hosts: rsyslog_clients
  become: yes
  vars:
    rsyslog_server_ip: 192.168.0.195
    rsyslog_server_fqdn:
    - app1.example.com
    - app2.example.com

  tasks:
  - name: Install dependencies
    apt:
      name: [rsyslog, rsyslog-gnutls, openssl]
      state: present

  - name: Create SSL directory
    file:
      path: /etc/ssl/rsyslog
      state: directory
      owner: root
      group: syslog
      mode: '0755'

  - name: Copy CA Certificate from Control Node to Client
    copy:
      src: /tmp/rsyslog_ca.crt
      dest: /etc/ssl/rsyslog/rsyslog_ca.crt
      owner: root
      group: syslog
      mode: '0644'

  - name: Generate Unique Client Key and CSR
    command: |
      openssl req -new -nodes
        -newkey rsa:2048
        -keyout /etc/ssl/rsyslog/rsyslog.key
        -out /etc/ssl/rsyslog/{{ inventory_hostname }}.csr
        -subj "/CN={{ inventory_hostname }}.example.com"
    # args:
    #   creates: "/etc/ssl/rsyslog/{{ inventory_hostname }}.csr"

  - name: Set key permissions
    file:
      path: /etc/ssl/rsyslog/rsyslog.key
      owner: root
      group: syslog
      mode: '0640'

  - name: Fetch CSR to Control Node
    fetch:
      src: "/etc/ssl/rsyslog/{{ inventory_hostname }}.csr"
      dest: "/tmp/{{ inventory_hostname }}.csr"
      flat: yes

- name: Sign Client Certificates on Server
  hosts: rsyslog_server
  become: yes
  tasks:
    - name: Copy CSRs to Server
      copy:
        src: "/tmp/{{ item }}.csr"
        dest: "/tmp/{{ item }}.csr"
      loop: "{{ groups['rsyslog_clients'] }}"

    - name: Sign Certificates with CA Key
      command: |
        openssl x509 -req -days 365
          -in /tmp/{{ item }}.csr
          -CA /etc/ssl/rsyslog/rsyslog.crt
          -CAkey /etc/ssl/rsyslog/rsyslog.key
          -CAcreateserial
          -out /tmp/{{ item }}.crt
      loop: "{{ groups['rsyslog_clients'] }}"
      # args:
      #   creates: "/tmp/{{ item }}.crt"

    - name: Fetch Signed Certificates back to Control Node
      fetch:
        src: "/tmp/{{ item }}.crt"
        dest: "/tmp/{{ item }}.crt"
        flat: yes
      loop: "{{ groups['rsyslog_clients'] }}"

- name: Deploy Signed Certificates to Clients
  hosts: rsyslog_clients
  become: yes
  vars:
    rsyslog_server_ip: 192.168.0.195
    rsyslog_server_fqdn: "log.example.com"

  tasks:
  - name: Copy final Signed Certificate to Client
    copy:
      src: "/tmp/{{ inventory_hostname }}.crt"
      dest: "/etc/ssl/rsyslog/rsyslog.crt"
      owner: root
      group: syslog
      mode: '0644'

  - name: Allow rsyslog to access SSL certs in AppArmor (Client)
    lineinfile:
      path: /etc/apparmor.d/local/usr.sbin.rsyslogd
      line: "/etc/ssl/rsyslog/* r,"
      create: yes
    notify: reload apparmor client

  - name: Deploy SSL configuration for rsyslog client
    template:
      src: templates/rsyslog-client-ssl.conf.j2
      dest: /etc/rsyslog.d/ssl.conf
    notify: restart rsyslog

  handlers:
  - name: restart rsyslog
    service:
      name: rsyslog
      state: restarted

  - name: reload apparmor client
    service:
      name: apparmor
      state: reloaded

