---
- name: Configure SSL for Rsyslog Server
  hosts: rsyslog_server
  vars:
    rsyslog_client_fqdn: "log.example.com"
  become: yes
  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install OpenSSL
    apt:
      name:
      - rsyslog
      - rsyslog-gnutls
      - openssl
      state: present

  - name: Ensure /etc/ssl is traversable
    file:
      path: /etc/ssl
      state: directory
      mode: '0755'

  - name: Ensure /etc/ssl is owned by root
    file:
      path: /etc/ssl
      owner: root
      group: root
      mode: '0755'

  - name: Create SSL directory
    file:
      path: /etc/ssl/rsyslog
      state: directory
      owner: root
      group: syslog
      mode: '0755'

  - name: Generate self-signed SSL certificate
    command: |
      openssl req -new -x509 -days 365 -nodes
        -newkey rsa:2048
        -out /etc/ssl/rsyslog/rsyslog.crt
        -keyout /etc/ssl/rsyslog/rsyslog.key
        -subj "/CN={{ rsyslog_client_fqdn }}"
        -addext "basicConstraints=critical,CA:TRUE"
    args:
      creates: /etc/ssl/rsyslog/rsyslog.key


  - name: Set permissions on SSL key
    file:
      path: /etc/ssl/rsyslog/rsyslog.key
      owner: root
      group: syslog
      mode: '0640'

  - name: Set permissions on SSL certificate
    file:
      path: /etc/ssl/rsyslog/rsyslog.crt
      owner: root
      group: syslog
      mode: '0644'

  - name: Allow rsyslog to access SSL certs in AppArmor
    lineinfile:
      path: /etc/apparmor.d/local/usr.sbin.rsyslogd
      line: "/etc/ssl/rsyslog/* r,"
      create: yes
    notify: reload apparmor

  - name: Deploy SSL configuration for rsyslog
    template:
      src: templates/rsyslog-server-ssl.conf.j2
      dest: /etc/rsyslog.d/ssl.conf
    notify: restart rsyslog

  - name: Ensure UFW is enabled and running
    ufw:
      state: enabled

  - name: To not block your self when connecting via SSH, allow port 22
    ufw:
      rule: allow
      port: 22
      proto: tcp

  - name: Deny firewall UDP 6514 for traditional syslog
    ufw:
      rule: deny
      port: 514
      proto: udp

  - name: Open firewall TCP 6514 for TLS syslog
    ufw:
      rule: allow
      port: 6514
      proto: tcp


  handlers:
  - name: restart rsyslog
    service:
      name: rsyslog
      state: restarted

  - name: reload apparmor
    service:
      name: apparmor
      state: reloaded

- name: Fetch SSL certificate from Rsyslog Server to Ansible Control Node
  hosts: rsyslog_server
  become: yes
  tasks:
  - name: Fetch SSL certificate from server
    fetch:
      src: /etc/ssl/rsyslog/rsyslog.crt
      dest: /tmp/rsyslog.crt
      flat: yes

- name: Configure SSL for Rsyslog Clients
  hosts: rsyslog_clients
  become: yes
  vars:
    rsyslog_server_ip: 192.168.0.195
    rsyslog_server_fqdn: "log.example.com"
  tasks:
  - name: Install OpenSSL
    apt:
      name:
      - rsyslog
      - rsyslog-gnutls
      - openssl
      state: latest

  - name: Create SSL directory
    file:
      path: /etc/ssl/rsyslog
      state: directory
      owner: root
      group: syslog
      mode: '0755'

  - name: Copy SSL certificate from control node to client
    copy:
      src: /tmp/rsyslog.crt
      dest: /etc/ssl/rsyslog/rsyslog.crt
      owner: root
      group: syslog
      mode: '0644'

  - name: Allow rsyslog to access SSL certs in AppArmor (Client)
    lineinfile:
      path: /etc/apparmor.d/local/usr.sbin.rsyslogd
      line: "/etc/ssl/rsyslog/* r,"
      create: yes
    notify: reload apparmor client

  - name: Deploy SSL configuration for rsyslog client
    template:
      src: templates/rsyslog-client-ssl.conf.j2
      dest: /etc/rsyslog.d/ssl.conf
    notify: restart rsyslog

  handlers:
  - name: restart rsyslog
    service:
      name: rsyslog
      state: restarted

  - name: reload apparmor client
    service:
      name: apparmor
      state: reloaded

